account_number = "576277063358"
environment    = "dev"
service_name              = "blackberry_pull_request"
#application_source_branch = ""
repo_name                 = "githubworkflowterraform"
#assignment_group          = "Group Data Banana"
deployment_item           = "Glue jobs"
